import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { MovieCard } from "../components/MovieCard";
import { addMovies, setFeaturedMovie } from "../store/reducer/moviesReducer";
import styles from "../styles/Home.module.css";
import { IoHeartSharp, IoStarSharp } from "react-icons/io5";
import { fetchMovies } from "../utils/fetchMovies";

const Home: NextPage = () => {
  const movies = useSelector((state: any) => state.movies.movies);
  const featuredMovie = useSelector((state: any) => state.movies.featuredMovie);
  const dispatch = useDispatch();
  let fetchedMovies: any = {};
  const fetchData = async () => {
    fetchedMovies = await fetchMovies();
    console.log(fetchedMovies);
    dispatch(setFeaturedMovie(fetchedMovies.image));
    dispatch(addMovies(fetchedMovies.videos));
  };

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Movies master</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.hero}>
          <h1 className={styles.hero__title}>
            Welcome to Movies Master by Yosef Blandin
          </h1>
        </section>

        <nav className={styles.navContainer}>
          <ul>
            <li className={styles.nav__element}>
              {" "}
              <IoHeartSharp fontSize={"2rem"} /> Your Favorite Movies
            </li>
            <li className={styles.nav__element}>
              {" "}
              <IoStarSharp fontSize={"2rem"} /> Top Actors
            </li>
          </ul>
        </nav>

        <section className={styles.cardsContainer}>
          {movies.map((movie: any) => (
            <MovieCard
              key={movie.description}
              img={movie.image.url}
              description={movie.description}
              contentType={movie.contentType}
            />
          ))}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
